"""Storage protocol used by API routes and future editing/export services."""

from typing import Protocol

from backend.app.models.schemas import Itinerary, TripListResponse, TripVersionsResponse


class TripRepository(Protocol):
    def create(self, itinerary: Itinerary) -> Itinerary: ...

    def get_current(self, trip_id: str) -> Itinerary: ...

    def get_version(self, trip_id: str, version: int) -> Itinerary: ...

    def list(self, *, limit: int, cursor: str | None = None) -> TripListResponse: ...

    def save_version(self, itinerary: Itinerary, *, expected_version: int) -> Itinerary: ...

    def list_versions(self, trip_id: str) -> TripVersionsResponse: ...

    def delete(self, trip_id: str) -> None: ...
